#!/usr/bin/env bash
# dpw@larkspur.localdomain
# 2025-09-22 15:03:00
#

set -eu

while [[ $# -gt 0 ]]
do 
    case $1 in
        run)
            mdbook serve --hostname 0.0.0.0
            shift
            ;;
        *)
            mdbook build
            shift
            ;;
    esac
done
